Exit if no indexes exist
yoshuawuyts/choo-log pull request #66
Opened 2017-04-18 18:17 UTC by toddself

Fixes: https://github.com/yoshuawuyts/choo-log/issues/57

2017-04-18 18:18 UTC, toddself commented
![image](https://cloud.githubusercontent.com/assets/193412/25146466/cde32fbc-2428-11e7-91cf-fac4b314eceb.png)

2017-04-19 09:54 UTC, yoshuawuyts requested changes

2017-04-19 09:54 UTC, yoshuawuyts commented on index.js
> +      if (index < 0) return
This should probably be `return log.info('render')` so we still log the `'render'` event - we might drop it otherwise :(

2017-04-24 20:36 UTC, s3ththompson commented
Are there additional changes necessary for this PR to land?

2017-04-24 22:36 UTC, yoshuawuyts approved these changes

2017-04-24 22:36 UTC, merged

2017-04-24 22:36 UTC, yoshuawuyts commented
`v6.1.2`